
# html lang
language: zh-Hans

# main menu navigation
menu:
  home: /
  # archives: /archives
  tags: /tags
  # categories: /categories
  # search: /search
  rss: /atom.xml

# website logo
logo: https://www.hufeifei.cn/favicon.jpg

# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/xoxo.css

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/xoxo.js

# switch
show_excerpt: true
show_date: true
#footer
index_page: https://www.hufeifei.cn
blog_page: https://blog.hufeifei.cn
github: https://github.com/holmofy

friends:
  - name: draveness
    url: https://draveness.me/
  - name: CoolShell
    url: https://coolshell.cn/
  - name: martin kleppmann
    url: https://martin.kleppmann.com/
  - name: skywind
    url: http://www.skywind.me/blog/